apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
type: Opaque
stringData:
  DB_PASSWORD: {{ .Values.db.password }}
  APP_GIPHY_TOKEN: {{ .Values.app.giphyToken }}
  SLACK_SIGNING_SECRET : {{ .Values.app.slackSigningSecret }} 
